services:
- docker
script:
- make
- ls -la | grep pdf
deploy:
  provider: releases
  api_key:
    secure: Ep5VOvNyqHYPljIV310WCLsSWy/bcSyNDw0Z4PQoxKWWufMwSxiulQ3uRVwBn8dhYYY4u89hdxx9WvT2g7O6smOzgY7bElWHPGO2OLHdgKpobaK2U2+KiGDjXFgepvLAxs2kBR76s06/R/TiwlY3/Svy+0fqGyDJERuf20bMkRzsKIubviomofyFSMz68pr6ICyswfKj3B6W8CFZNfUO0Rf1DPRIl3aXrsKcQ82aXNSFjMPtb6OKMjNOEh/P5RHrXvFneCYX5w6xdZ9MF4vZvR71IzFUHAUuft8piVx69W7MQBzWaxwUCuVpolzmDbUReLGqQjqeLEUYaY/QDusMpegHfAj/wQeVZxYqvh0xcRTS5ihtaaj0dNrIjcqb40eQm34OOxS2mqPDZbXw2Vs73n1zoEF7XNnQrlSLhY4F7DWr3UKIsrQfIi1hZK5gRXVDI2skpSfMEJVenUF0DD2LPkkHfhUtXHBFxUaYv1CSEUYLn18mB/J9+ceCqJOQt7vmORhvViKpWqIMyoGld+/XZzHIY95xpKeD6ForgKIi/y5XsAzKDyEssMU3kLQExSZkQ9LFQ1nhswckFqWuzZxVRQcjox7Aqu8WVndUoZTH6HC2GJJfSgvuaSwPro6OfQH04OlXrRTnuWGwE49e5WLgw2sM4DdI3A45vDTw5Jo3t+k=
  file: thesis.pdf
  skip_cleanup: true
  on:
    repo: uniba-ktr/ThesTeX
    tags: true
